---
title: "Project Name"
author: "kattur"
date: "" 
output: html_document 
#runtime: shiny

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = getwd())
library(DT)
library(raster)
library(knitr)
library(stringr)
library(dplyr)
library(kableExtra)
```


## Location of hosts

Here we provide tables showing the locations of 

<br>


```{r host_data, include=FALSE}


species_l1 <- read.csv("data/host_loc_sp_level1.csv", stringsAsFactors = FALSE)

species_l2 <- read.csv("data/host_loc_sp_level2.csv", stringsAsFactors = FALSE)

species_l3 <- read.csv("data/host_loc_sp_level3.csv", stringsAsFactors = FALSE)

genus_l1 <- read.csv("data/host_loc_gen_level1.csv", stringsAsFactors = FALSE)

genus_l2 <- read.csv("data/host_loc_gen_level2.csv", stringsAsFactors = FALSE)

genus_l3 <- read.csv("data/host_loc_gen_level3.csv", stringsAsFactors = FALSE)


```

  

```{r}
library(DT)

species_l1_dt <- datatable(species_l1,
                             rownames = FALSE,
                             filter = 'top')

species_l2_dt <- datatable(species_l2,
                             rownames = FALSE,
                             filter = 'top')

species_l3_dt <- datatable(species_l3,
                             rownames = FALSE,
                             filter = 'top')

genus_l1_dt <- datatable(genus_l1,
                             rownames = FALSE,
                             filter = 'top')


genus_l2_dt <- datatable(genus_l2,
                             rownames = FALSE,
                             filter = 'top')

#genus_l3_dt <- DT::renderDT(datatable(genus_l3,
#                             rownames = FALSE,
#                             filter = 'top')) ## table too large, so need to render using shiny

genus_l3_dt <- datatable(genus_l3,
                             rownames = FALSE,
                             filter = 'top') 
```

## {.tabset}

### Species{.tabset .col-leftmid}
#### Level.3 
```{r ,echo = FALSE}
species_l3_dt   
```
#### Level.2
```{r ,echo = FALSE}
species_l2_dt
```
#### Level.1
```{r ,echo = FALSE}
species_l1_dt
```
##### {-}

### {-}

### Genus{.tabset .col-leftmid}
#### Level.3 
```{r ,echo = FALSE, warning = FALSE}
genus_l3_dt   
```
#### Level.2
```{r ,echo = FALSE}
genus_l2_dt
```
#### Level.1
```{r ,echo = FALSE}
genus_l1_dt
```

##### {-}

### {-}

## {-}




<br>


